export const institutes = [
  {
    id: 'sharon-beauty',
    name: 'Sharon Beauty',
    initials: 'SB',
    color: 'bg-pink-200',
    rating: 4.8,
    reviews: 127,
    category: 'Soins visage',
    city: 'Alger',
    district: 'Hydra',
    address: '23 rue Hassiba, Hydra, Alger',
    phone: '0555 12 34 56',
    hours: '9h – 20h',
    days: 'Lun – Sam',
    reservations: 247,
    description: 'Un salon modernisé dédié à votre beauté. Soins du visage, massage, coiffure, manucure… profitez d\'un moment de détente et de qualité dans un cadre élégant et chaleureux.',
    verified: true,
    popular: true,
    isNew: false,
    services: [
      { id: 1, name: 'Soin visage hydratant', duration: 60, price: 2500, icon: '💆', description: 'Nettoyage en profondeur, hydratation intense et massage relaxant du visage et du cou.' },
      { id: 2, name: 'Massage relaxant corps', duration: 80, price: 3800, icon: '🤲', description: 'Massage aux huiles essentielles pour libérer les tensions musculaires.' },
      { id: 3, name: 'Manucure semi-permanent', duration: 50, price: 1800, icon: '💅', description: 'Soin complet des mains, pose de vernis semi-permanent au choix parmi 80 couleurs.' },
      { id: 4, name: 'Épilation sourcils', duration: 20, price: 600, icon: '✨', description: 'Sculpture précise des sourcils au fil ou à la cire pour un regard expressif.' },
      { id: 5, name: 'Soin anti-âge premium', duration: 75, price: 4200, icon: '🌟', description: 'Traitement complet anti-rides et anti-taches avec des actifs de haute technologie.' },
      { id: 6, name: 'Épilation jambes complètes', duration: 45, price: 1400, icon: '🦵', description: 'Épilation à la cire chaude pour des jambes douces et soyeuses pour 4 à 6 semaines.' },
    ],
    team: [
      { id: 1, name: 'Camille B.', specialty: 'Spécialiste soins visage', rating: 4.9, reviews: 247, color: 'bg-purple-500' },
      { id: 2, name: 'Nadia H.', specialty: 'Massage & Bien-être', rating: 4.8, reviews: 183, color: 'bg-blue-500' },
      { id: 3, name: 'Sara M.', specialty: 'Manucure & pédicure', rating: 4.7, reviews: 156, color: 'bg-teal-500' },
    ],
    clientReviews: [
      { id: 1, name: 'Clara D.', initial: 'C', color: 'bg-pink-500', rating: 5, time: 'Il y a 4 jours', comment: 'Je suis ravie de ma prestation ! L\'esthéticienne était absolument adorable et très professionnelle. Très belle découverte, je reviendrai certainement.', reply: 'Merci Clara pour ce magnifique avis ! C\'est un plaisir de vous accueillir et nous espérons vous revoir très bientôt.' },
      { id: 2, name: 'Dorlane F.', initial: 'D', color: 'bg-orange-500', rating: 5, time: 'Il y a 4 jours', comment: 'La prestation est parfaite, je suis très satisfaite de ma manucure et de la pose de vernis. Les produits sont de qualité, le résultat est magnifique.' },
      { id: 3, name: 'Rym K.', initial: 'R', color: 'bg-red-400', rating: 4, time: 'Il y a 1 semaine', comment: 'Très bon endroit, ambiance agréable et équipe souriante. Le soin visage était excellent. Légère attente à l\'accueil mais rien de grave.' },
    ],
    nearby: [
      { id: 'nour-beauty', name: 'Nour Beauty', initials: 'NB', color: 'bg-indigo-200', rating: 4.7 },
      { id: 'jolie-spa', name: 'Jolie Spa', initials: 'JS', color: 'bg-green-200', rating: 4.5 },
      { id: 'clina-beauty', name: 'Clina Beauty', initials: 'CB', color: 'bg-amber-200', rating: 4.4 },
    ],
  },
  {
    id: 'nour-beauty',
    name: 'Nour Beauty',
    initials: 'NB',
    color: 'bg-indigo-200',
    rating: 4.7,
    reviews: 89,
    category: 'Massage',
    city: 'Oran',
    district: 'Centre',
    address: '15 rue Larbi Ben Mhidi, Oran',
    phone: '0555 98 76 54',
    hours: '9h – 19h',
    days: 'Lun – Sam',
    reservations: 183,
    description: 'Institut spécialisé en massages et bien-être. Un espace de relaxation absolue au cœur d\'Oran.',
    verified: true,
    popular: false,
    isNew: false,
    services: [
      { id: 1, name: 'Massage suédois', duration: 60, price: 3000, icon: '🤲', description: 'Massage classique aux huiles.' },
      { id: 2, name: 'Massage aux pierres chaudes', duration: 90, price: 4500, icon: '🌋', description: 'Massage aux pierres volcaniques.' },
    ],
    team: [
      { id: 1, name: 'Amira S.', specialty: 'Massage & Bien-être', rating: 4.8, reviews: 120, color: 'bg-indigo-500' },
    ],
    clientReviews: [],
    nearby: [],
  },
  {
    id: 'jolie-spa',
    name: 'Jolie Spa',
    initials: 'JS',
    color: 'bg-green-200',
    rating: 4.5,
    reviews: 64,
    category: 'Hammam',
    city: 'Alger',
    district: 'Bab El Oued',
    address: '8 rue Didouche Mourad, Alger',
    phone: '0555 11 22 33',
    hours: '10h – 21h',
    days: 'Tous les jours',
    reservations: 95,
    description: 'Spa et hammam traditionnel revisité dans un cadre luxueux.',
    verified: true,
    popular: false,
    isNew: true,
    services: [
      { id: 1, name: 'Hammam traditionnel', duration: 90, price: 2000, icon: '♨️', description: 'Expérience hammam complète.' },
    ],
    team: [],
    clientReviews: [],
    nearby: [],
  },
  {
    id: 'clina-beauty',
    name: 'Clina Beauty',
    initials: 'CB',
    color: 'bg-amber-200',
    rating: 4.4,
    reviews: 53,
    category: 'Manucure',
    city: 'Constantine',
    district: 'Centre',
    address: '5 rue Salah Bey, Constantine',
    phone: '0555 44 55 66',
    hours: '9h – 18h',
    days: 'Lun – Ven',
    reservations: 78,
    description: 'Spécialiste manucure et pédicure dans un cadre moderne.',
    verified: false,
    popular: false,
    isNew: true,
    services: [
      { id: 1, name: 'Manucure classique', duration: 45, price: 1200, icon: '💅', description: 'Soin des ongles complet.' },
    ],
    team: [],
    clientReviews: [],
    nearby: [],
  },
  {
    id: 'top-beauty',
    name: 'Top Beauty',
    initials: 'TB',
    color: 'bg-pink-100',
    rating: 4.9,
    reviews: 23,
    category: 'Soins visage',
    city: 'Alger',
    district: 'El Biar',
    address: '12 rue des Oliviers, El Biar, Alger',
    phone: '0555 77 88 99',
    hours: '9h – 20h',
    days: 'Lun – Sam',
    reservations: 34,
    description: 'Nouveau salon de beauté avec les dernières technologies.',
    verified: true,
    popular: false,
    isNew: true,
    services: [],
    team: [],
    clientReviews: [],
    nearby: [],
  },
  {
    id: 'institut-nawel',
    name: 'Institut Nawel',
    initials: 'IN',
    color: 'bg-blue-100',
    rating: 4.6,
    reviews: 8,
    category: 'Épilation',
    city: 'Oran',
    district: 'Bir El Djir',
    address: '3 rue des Roses, Bir El Djir, Oran',
    phone: '0555 33 22 11',
    hours: '9h – 19h',
    days: 'Mar – Sam',
    reservations: 12,
    description: 'Institut d\'épilation et soins corporels.',
    verified: false,
    popular: false,
    isNew: true,
    services: [],
    team: [],
    clientReviews: [],
    nearby: [],
  },
]

export const categories = ['Soins visage', 'Manucure', 'Massage', 'Épilation', 'Hammam']

export const cities = ['Alger', 'Oran', 'Constantine', 'Annaba', 'Blida', 'Tlemcen']

export const CALENDAR = {
  days: ['LU', 'MA', 'ME', 'JE', 'VE', 'SA', 'DI'],
  months: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
}

export const TIME_SLOTS = {
  morning: ['09:00', '09:30', '10:00', '10:30', '11:00', '11:30'],
  afternoon: ['14:00', '14:30', '15:00', '15:30', '16:00', '17:00'],
}

export const UNAVAILABLE_SLOTS = ['09:00', '11:00', '15:00', '16:00']